/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/app/printers/{printer_uuid}/camera": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register camera to Connect by user. */
        post: {
            parameters: {
                query?: {
                    origin?: "WEB" | "OTHER";
                };
                header?: never;
                path: {
                    printer_uuid: components["parameters"]["printer_uuid_param"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description **Created camera with token.** */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["camera_response"];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401-app"];
                403: components["responses"]["403-app"];
                503: components["responses"]["503"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/c/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload snapshot to Connect */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "image/jpg": string;
                };
            };
            responses: {
                204: components["responses"]["204"];
                400: components["responses"]["400"];
                401: components["responses"]["401-p"];
                403: components["responses"]["403-p"];
                404: components["responses"]["404"];
                503: components["responses"]["503"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/c/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update camera attributes */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["camera_request"];
                };
            };
            responses: {
                /** @description **OK** */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["camera_response"];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401-p"];
                403: components["responses"]["403-p"];
                503: components["responses"]["503"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example T0nSPU2v05v0pJeKYFYV */
        token: string;
        /** @description Network information */
        network_info: {
            /**
             * @description Hardware address of ethernet port.
             * @example 0a:bc:12:34:56:7f
             */
            lan_mac?: string;
            /**
             * @description IPv4 address of ethernet port.
             * @example 192.168.1.5
             */
            lan_ipv4?: string;
            /**
             * @description IPv6 address of ethernet port.
             * @example 2e0a::1234:5678:abcd:efab/64
             */
            lan_ipv6?: string;
            /**
             * @description Hardware address of Wi-Fi device.
             * @example 0a:bc:12:34:ab:7f
             */
            wifi_mac?: string;
            /**
             * @description IPv4 address of Wi-Fi device.
             * @example 192.168.1.6
             */
            wifi_ipv4?: string;
            /**
             * @description IPv6 address of Wi-Fi device.
             * @example 2e0a::1234:5678:abcd:0123/64
             */
            wifi_ipv6?: string;
            /**
             * @description SSID of Wi-Fi network which is used by Wi-Fi device.
             * @example PublicWiFi
             */
            wifi_ssid?: string;
        };
        camera_resolution: {
            /** @example 640 */
            width?: number;
            /** @example 480 */
            height?: number;
        };
        camera_capabilities: ("trigger_scheme" | "imaging" | "resolution" | "focus")[];
        /** @description Configuration of the camera */
        camera_config: {
            /** @example null */
            camera_id?: string;
            /**
             * @description Path to the driver
             * @example /dev/video0
             */
            path?: string;
            name: components["schemas"]["device_name"];
            /** @example V4L2 */
            driver?: string;
            /**
             * @description Type of snapshot trigger scheme. Manual, layer, gcode only for LINK cameras
             * @default THIRTY_SEC
             * @example THIRTY_SEC
             * @enum {string}
             */
            trigger_scheme: "MANUAL" | "EACH_LAYER" | "FIFTH_LAYER" | "GCODE" | "TEN_SEC" | "THIRTY_SEC" | "SIXTY_SEC" | "TEN_MIN";
            resolution?: components["schemas"]["camera_resolution"];
            network_info?: components["schemas"]["network_info"];
            /**
             * @description Firmware version of the camera
             * @example 1.0.0
             */
            firmware?: string;
            /**
             * @description Manufacturer of the camera
             * @example Prusa
             */
            manufacturer?: string;
            /**
             * @description Model of the camera
             * @example C920
             */
            model?: string;
        };
        /** @description Configuration of the camera */
        camera_options: {
            available_resolutions?: components["schemas"]["camera_resolution"][];
        };
        /**
         * @description Camera origin whether it is registered by web (WEB) or by printer (LINK) or manually via camera api (OTHER)
         * @enum {string}
         */
        camera_origin: "LINK" | "WEB" | "OTHER";
        camera_request: {
            config: components["schemas"]["camera_config"];
            options?: components["schemas"]["camera_options"];
            capabilities?: components["schemas"]["camera_capabilities"];
        };
        camera_response: {
            id: number;
            name?: components["schemas"]["device_name"];
            config?: components["schemas"]["camera_config"];
            options?: components["schemas"]["camera_options"];
            capabilities?: components["schemas"]["camera_capabilities"];
            team_id: components["schemas"]["team_id"];
            printer_uuid: components["schemas"]["printer_uuid"];
            token?: components["schemas"]["token"];
            origin: components["schemas"]["camera_origin"];
            /** @description Timestamp of camera deletion. Deleted cameras are listed only in job detail! */
            deleted?: number;
            /** @description True if the registration process of camera is finished */
            registered: boolean;
            /** @description Sort order of the cameras per printer! For now it is not possible to change the camera's sort order */
            sort_order?: number;
        };
        status: {
            /** @description Error code */
            code: string;
            /** @description Human readable error message */
            message: string;
        };
        /**
         * @description Name defined by user
         * @example Olomouc
         */
        device_name: string | null;
        /** @description Team id. 0 is reserved for anonymous. */
        team_id: number;
        /**
         * @description Printer UUID - can be found in the url in printer detail or in the printer settings tab
         * @example cfed5dce-86f4-4d7c-a198-9a81b176369f
         */
        printer_uuid: string;
    };
    responses: {
        /**
         * @description **No Content**
         *     Data was accepted by the server.
         */
        204: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /**
         * @description **Found**
         *     Moved temporarily.
         */
        302: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description **See other** */
        303: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description **Response not modified** */
        304: {
            headers: {
                "Last-Modified": components["headers"]["Last-Modified"];
                etag: components["headers"]["etag"];
                [name: string]: unknown;
            };
            content?: never;
        };
        /**
         * @description **Bad Request**
         *     Some data received is not valid. Typically this happens for POST requests with incorrect structure or a path argument was sent that is not defined in the URL.
         */
        400: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description **Not Found** Entity not found or invalid auth token. */
        404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["status"];
            };
        };
        /**
         * @description **Conflict**
         *     Request could not be processed because the requested change would create a conflict in the database.
         */
        409: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["status"];
            };
        };
        /**
         * @description **Payload too large**
         *     Chunked request was too large.
         */
        413: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["status"];
            };
        };
        /** @description **Too many requests** */
        429: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["status"];
            };
        };
        /**
         * @description **Service Unavailable**
         *     Service is unavailable at this moment. Try again later.
         */
        503: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
                "application/json": components["schemas"]["status"];
            };
        };
        /**
         * @description **Unauthorized**
         *     Missing security token or it is not valid.
         */
        "401-app": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["status"];
            };
        };
        /**
         * @description **Unauthorized**
         *     Missing security token or it is not valid.
         */
        "401-p": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["status"];
            };
        };
        /**
         * @description **Forbidden**
         *     Security token is not valid or is outdated. Or user doesn't has rights for perform action.
         */
        "403-app": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["status"];
            };
        };
        /**
         * @description **Forbidden**
         *     Security token is not valid or is outdated.
         */
        "403-p": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["status"];
            };
        };
    };
    parameters: {
        printer_uuid_param: components["schemas"]["printer_uuid"];
    };
    requestBodies: never;
    headers: {
        "Last-Modified": string;
        etag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
